backend/earo_travel_tracker/earo_travel_tracker/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from django.conf.urls.static import static
from django.conf import settings
# Earo_travel_tracker imports
from traveler.urls import urlpatterns as traveler
from trip.urls import api_url_patterns as trip_api
from trip.urls import urlpatterns as trip


# url patterns for restful APIs
# ***** Disabled API URLs until authentication is enforced *****
# api_urlpatterns = [
#     path('traveler/', include(traveler_api)),
#     path('trip/', include(trip_api)),
# ]

# All url patterns
urlpatterns = [
    path('administration/', admin.site.urls),
    path('admin/', include('grappelli.urls')),
    # path('api/', include(api_urlpatterns)),
    path('traveler/', include(traveler)),
    path('trip/', include(trip)),
    path('accounts/', include('django.contrib.auth.urls')),
    path('oauth2/', include('django_auth_adfs.urls')),
    # Redirect domain root to List trip
    path('', RedirectView.as_view(pattern_name='u_list_my_trips')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

backend/earo_travel_tracker/trip/urls.py
"""
All url mappings for the trip app are defined here
"""
from django.urls import path
# Third party app imports
from rest_framework import routers
# Earo_travel_tracker imports
from .views import (
    TripViewSet, TripTravelerDependantsViewSet, TripApprovalViewSet, TripItineraryViewSet,
    TripCreateView, TripDetailView, TripUpdateView, TripDeleteView,
    TripListView, TripPOETCreateView, TripPOETUpdateView ,TripItineraryListView,
    TripItineraryCreateView, TripItineraryUpdateView, TripItineraryDeleteView, ApproveTripView,
    TripApprovalListView,
    )

router = routers.SimpleRouter()
router.register(r'trips', TripViewSet)
router.register(r'trip-traveler-dependants', TripTravelerDependantsViewSet)
router.register(r'trip-approval', TripApprovalViewSet)
router.register(r'trip-itinerary', TripItineraryViewSet)
api_url_patterns = router.urls


urlpatterns = [
    # trips
    path('new-trip', TripCreateView.as_view(), name='u_create_trip'),
    path('list-trips/ongoing', TripApprovalListView.as_view(),  {'filter_by': 'ongoing'},
    name='u_list_ongoing_trips'),
    path('list-trips/upcoming', TripApprovalListView.as_view(), {'filter_by': 'upcoming'},
        name='u_list_upcoming_trips'),
    path('list-trips/awaiting-approval', TripApprovalListView.as_view(),
        {'filter_by': 'awaiting_approval'}, name='u_list_awaiting_approval_trips'),
    path('list-trips/my-trips', TripListView.as_view(), name='u_list_my_trips'),
    path('update-trip/trip=<trip_id>', TripUpdateView.as_view(), name='u_update_trip'),
    path('trip-details/trip=<trip_id>', TripDetailView.as_view(), name='u_trip_details'),
    path('delete-trip/trip=<trip_id>', TripDeleteView.as_view(), name='u_delete_trip'),
    # trip poet
    path('trip-poet/add/trip=<trip_id>', TripPOETCreateView.as_view(), name='add_poet'),
    path('trip-poet/update/<trip_id>/poet=<poet_id>', TripPOETUpdateView.as_view(),
        name='update_poet'),
    # trip itinerary
    path('trip-itinerary/new-leg/trip=<trip_id>', TripItineraryCreateView.as_view(),
        name='u_create_trip_itinerary'),
    path('trip-itinerary/trip=<trip_id>', TripItineraryListView.as_view(),
        name='u_list_trip_itinerary'),
    path('trip-itinerary/trip-leg=<leg_id>', TripItineraryUpdateView.as_view(),
        name='u_update_trip_itinerary'),
    path('trip-itinerary/trip=<trip_id>', TripItineraryDeleteView.as_view(),
        name='u_delete_trip_itinerary'),
    # traveler dependants
    # trip approval
    path('trip-approval/approval_request=<approval_id>', ApproveTripView.as_view(),
        name='u_approve_trip'),
]

backend/earo_travel_tracker/traveler/models.py
"""
Data models for the traveler app are defined in this file.
"""
import logging
# django imports
from django.db import models
from django.conf import settings
from django.urls import reverse
from django.contrib.auth.models import Group
from django.utils import timezone

LEVELS_OF_SECURITY = (
    ('1','Level 1'),
    ('2','Level 2'),
    ('3','Level 3'),
)


logger = logging.getLogger(__name__)

class Approver(models.Model):
    """
    All users who are designated as approvers have to be stored in the DB table associated with
    this model as foreign key references to their user account.
    All approvers set on other models (Departments, CountrySecurityLevel, TravelerProfile) should
    be referenced to this model.
    """
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.PROTECT, null=False,
                            blank=False, related_name="approver")
    security_level = models.CharField(max_length=1, choices=LEVELS_OF_SECURITY, null=False,
                            blank=False, default=1, verbose_name="Security Approval Level")
    is_active = models.BooleanField(null=False, blank=True, default=True)

    def __str__(self):
        return " ".join([self.user.first_name, self.user.last_name])

    def get_absolute_url(self):
        """
        absolute url to an Approver instance
        """
        return reverse('view_approver', kwargs={'approver_id': self.id})

    def active_delegation_exists(self):
        """
        Check if there is an existing active delegation.
        """
        return ApprovalDelegation.objects.filter(approver=self).filter(active=True).exists()

    def get_delegate(self):
        """Get the approver to whom approval has been delegated"""
        return self.get_active_delegation().approver

    def get_active_delegation(self):
        """Get the active delegation"""
        return ApprovalDelegation.objects.filter(approver=self, active=True)[0]

    def add_to_approvers_group(self):
        """
        Add approver to approvers group when an approver is created.
        """
        if self._state.adding:
            try:
                approvers = Group.objects.get(name='approvers')
                approvers.user_set.add(self.user)
            except Group.DoesNotExist:
                logger.error("Approvers group doesn't exist. "
                    "Create the group and assign it the proper permissions.")

    def save(self, *args, **kwargs):
        self.add_to_approvers_group()
        return super().save(*args, **kwargs)

    class Meta:
        verbose_name = "Approver"
        verbose_name_plural = "Approvers"


class ApprovalDelegation(models.Model):
    """
    This class implements delegation of approval rights.
    """
    approver = models.ForeignKey(Approver, on_delete=models.PROTECT,
            related_name="delegating_approver", null=False, blank=False, db_index=True)
    delegate = models.ForeignKey(Approver, on_delete=models.PROTECT,
            related_name="delegate", null=False, blank=False, db_index=True)
    reason_for_delegation = models.TextField(max_length=500, blank=False, null=False)
    reason_for_revocation = models.TextField(max_length=500, blank=False, null=False)
    start_date = models.DateField(null=False, blank=False, default=timezone.now)
    end_date = models.DateField(null=False, blank=False)
    active = models.BooleanField(default=True, null=False)

    def get_absolute_url(self):
        """Permalink to an objects details"""
        return reverse('u_trip_details', kwargs={'approval_delegation_id':self.id})

    def revoke_approval_delegation(self, reason_for_revocation):
        """
        Enables an approver to revoke an existing delegation of their approval rights.
        """
        self.active = False
        self.reason_for_revocation = reason_for_revocation
        self.end_date = timezone.now().today()
        self.save()


class Departments(models.Model):
    """
    This class will implement departments model in the organization. This can also be
    functional units as my be appropriate for intents and purposes of this software.
    """
    department = models.CharField(max_length=50, null=False, blank=False, db_index=True)
    description = models.CharField(max_length=200, null=False, blank=False)
    security_level_1_approver = models.ForeignKey(Approver, on_delete=models.PROTECT,null=True,
                            blank=True, related_name="security_level_1_approver")
    security_level_2_approver = models.ForeignKey(Approver, on_delete=models.PROTECT,null=True,
                            blank=True, related_name="security_level_2_approver")


    def __str__(self):
        return self.department

    def get_absolute_url(self):
        """
        Define the url for model instances.
        """
        return reverse('u_department_details', args=(self.id,))

    class Meta:
        verbose_name = "Department"
        verbose_name_plural = "Departments"


class CountrySecurityLevel(models.Model):
    """
    This model lists countries and their associated security levels.
    """
    country = models.CharField(max_length=50, null=False, blank=False)
    security_level = models.CharField(max_length=1, choices=LEVELS_OF_SECURITY, null=False,
                            blank=False)
    security_level_3_approver = models.ForeignKey(Approver, null=True, blank=True,
                            on_delete=models.PROTECT)

    def __str__(self):
        return self.country

    def get_absolute_url(self):
        """
        Absolute URL to a Country Security Level instance.
        """
        return reverse('view_country', kwargs={"country_id": self.id})

    class Meta:
        verbose_name = "Country Security Level"
        verbose_name_plural = "Countries Security Levels"


class TravelerProfile(models.Model):
    """
    This model defines details of travelers. They can be employees, dependants of employees,
    consultants and partners. When it's employees or partners, there's a ONETOONE mapping to
    the USER model to associate with the travelers login account.
    """
    TRAVEL_CATEGORIES = (
        ('Employee', 'Employee'),
        ('Dependant', 'Consultant'),
        ('Consultant', 'Consultant'),
        ('Partners', 'Partners'),
    )

    department = models.ForeignKey(Departments, on_delete=models.PROTECT, null=True,
                                    blank=True)
    type_of_traveler = models.CharField(max_length=20, null=False, blank=False,
                                        choices=TRAVEL_CATEGORIES)
    nationality = models.CharField(max_length=30, null=False, blank=False)
    country_of_duty = models.ForeignKey(CountrySecurityLevel , null=True, blank=False,
                            on_delete=models.PROTECT, verbose_name="Country of duty / residence")
    contact_telephone = models.CharField(max_length=20, null=False, blank=False)
    contact_email = models.CharField(max_length=70, null=False, blank=True)
    user_account = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete= models.CASCADE,
                            blank=True, null=True)
    is_managed_by = models.ForeignKey('self', on_delete=models.SET_NULL, blank=True, null=True,
                                    db_index=True, verbose_name="Line Manager",
                                    related_name='Line_Manager')
    approver = models.ForeignKey(Approver, on_delete=models.PROTECT, blank=True,
                                null=True, related_name='trip_approver')

    def __str__(self):
        if self.user_account:
            return " ".join([self.user_account.first_name, self.user_account.last_name])
        return self.id

    def get_absolute_url(self):
        """Return the absolute url of the detail view of an instance."""
        return reverse('u_traveler_details', args=[(self.id)])

    def is_line_managed_by(self, user):
        """
        Check that the logged on user is the line manager of a traveler.
        The user argument should be an instance of settings.USER_MODEL
        """
        return bool(self.is_managed_by == user)

    def get_approver(self, security_level=1):
        """
        Get the approver for a traveler profile, given the security level
        return None if no approver is set.
        """
        approver = None
        # security level 1 approver
        print("passed arg type:", type(security_level)) # debugging code
        security_level = int(security_level)
        if security_level == 1:
            if self.approver is not None:
                print(self.approver) # Debug code
                approver = self.approver
            elif (self.department is not None and
                self.department.security_level_1_approver is not None):
                print("trying to get department approver") # debug code
                print(self.department.security_level_1_approver) # debug code
                approver = self.department.security_level_1_approver

        # security level 2 approver
        elif security_level == 2:
            approver = self.department.security_level_2_approver

        # security level 3 approver
        elif security_level == 3:
            approver = self.country_of_duty.security_level_3_approver
            print(f"sec level 3 {approver}")
        else:
            print("Invalid Security Level")  # debug code
            return None

        # check if approval has been delegated.
        if approver is not None and approver.active_delegation_exists():
            return approver.get_delegate()
        return approver

    class Meta:
        verbose_name = "Traveler Profile"
        verbose_name_plural = "Travelers Profiles"

backend/earo_travel_tracker/templates/base.html
{% extends 'foundation.html' %}
{% block body %}
<body class="hold-transition sidebar-mini">
<div class="wrapper">

  <!-- Navbar -->
  <nav class="main-header navbar navbar-expand navbar-white navbar-light navbar-fixed" id="top-nav">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
      </li>
    </ul>

    <!-- Right navbar links -->
    <ul class="navbar-nav ml-auto">
      <div class="container">
        <a class="btn btn-theme-primary float-right" href="{% url 'logout' %}">Logout</a>
      </div>

    </ul>
  </nav>
  <!-- /.navbar -->

  <!-- Main Sidebar Container -->
  <aside id="side-nav" class="main-sidebar sidebar-dark-primary elevation-4">
    <!-- Brand Logo -->
    <a href="#" class="brand-link">
      <span class="brand-text font-weight-light">Kenya-Somalia Travel Tracker</span>
    </a>

    <!-- Sidebar -->
    <div class="sidebar">
      <!-- Sidebar user panel (optional) -->
      <div class="user-panel mt-3 pb-3 mb-3 d-flex">
        <div class="info">
          <a href="#" class="d-block">{{request.user.first_name}}&nbsp;{{request.user.last_name}}</a>
        </div>
        
      </div>

      <!-- Sidebar Menu -->
      <nav class="mt-2">
        <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
          <!-- Add icons to the links using the .nav-icon class
               with font-awesome or any other icon font library -->
          <li class="nav-item">
            <a href="#" class="nav-link">
              <i class="nav-icon fa fa-user" aria-hidden="true"></i>
              <p>My Profile</p>
            </a>
          </li>
          <!-- Trips -->
          <li class="nav-item">
            <a href="#" class="nav-link">
              <i class="nav-icon fas fa fa-plane"></i>
              <p>
                Trips
                <i class="right fas fa-angle-left"></i>
              </p>
            </a>
            <ul class="nav nav-treeview">
              <li class="nav-item">
                <a href="{% url 'u_list_my_trips' %}" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>My Trips</p>
                </a>
              </li>
              <li class="nav-item">
                <a href="{% url 'u_create_trip' %}" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>New Trip</p>
                </a>
              </li>
              {% comment %}Allow only approvers to view these links{% endcomment %}
              {% if perms.traveler.add_approvaldelegation %}
              <li class="nav-item">
                <a href="{% url 'u_list_awaiting_approval_trips' %}" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>Awaiting My Approval</p>
                </a>
              </li>
              <li class="nav-item">
                <a href="{% url 'u_list_ongoing_trips' %}" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>Ongoing Trips</p>
                </a>
              </li>
              <li class="nav-item">
                <a href="{% url 'u_list_upcoming_trips' %}" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>Upcoming Trips</p>
                </a>
              </li>
              {% endif %}
            </ul>
          </li>
          <!-- /Trips -->
          <!-- Travelers -->
          {% if perms.traveler.add_travelerprofile or perms.traveler.view_travelerprofile %}
          <li class="nav-item">
            <a href="#" class="nav-link">
              <i class="fa fa-users"></i>
              <p>Travelers</p>
              <i class="right fas fa-angle-left"></i>
            </a>
            <ul class="nav nav-treeview">
              {% if perms.traveler.add_travelerprofile %}
              <li class="nav-item">
                <a href="{% url 'u_create_traveler' %}" class="nav-link">
                  <i class="fa fa-plus" aria-hidden="true"></i>&nbsp;
                  <p>Add Traveler</p>
                </a>
              </li>
              {% endif %}
              {% if perms.traveler.view_travelerprofile %}
              <li class="nav-item">
                <a href="{% url 'u_list_travelers' %}" class="nav-link">
                  <i class="fa fa-list-alt" aria-hidden="true"></i>&nbsp;
                  <p>Travelers Register</p>
                </a>
              </li>
              {% endif %}
            </ul>
          </li>
          <!-- /Travelers -->
          {% endif %}
          {% if perms.travelers.add_department or perms.travelers.view_department %}
          <!-- Departments -->
          <li class="nav-item">
            <a href="#" class="nav-link">
              <i class="fa fa-sitemap" aria-hidden="true"></i>
              <p>Departments</p>
              <i class="right fas fa-angle-left"></i>
            </a>
            <ul class="nav nav-treeview">
              {% if perms.traveler.add_department %}
              <li class="nav-item">
                <a href="{% url 'u_create_department' %}" class="nav-link">
                  <i class="fa fa-plus" aria-hidden="true"></i>&nbsp;
                  <p>Add Deparment</p>
                </a>
              </li>
              {% endif %}
              {% if perms.traveler.view_department %}
              <li class="nav-item">
                <a href="{% url 'u_list_departments' %}" class="nav-link">
                  <i class="fa fa-list-alt" aria-hidden="true"></i>&nbsp;
                  <p>Department Register</p>
                </a>
              </li>
              {% endif %}
            </ul>
          </li>
          <!-- /Departments -->
          {% endif %}
          {% if perms.travelers.add_countrysecuritylevel or perms.travelers.add_countrysecuritylevel%}
          <!-- Country Security Levels -->
          <li class="nav-item">
            <a href="#" class="nav-link">
              <i class="fa fa-globe-africa" aria-hidden="true"></i>
              <p>Country Security Levels</p>
              <i class="right fas fa-angle-left"></i>
            </a>
            <ul class="nav nav-treeview">
              {% if perms.traveler.add_countrysecuritylevel %}
              <li class="nav-item">
                <a href="{% url 'create_country' %}" class="nav-link">
                  <i class="fa fa-plus" aria-hidden="true"></i>&nbsp;
                  <p>Add Country</p>
                </a>
              </li>
              {% endif %}
              {% if perms.traveler.view_countrysecuritylevel %}
              <li class="nav-item">
                <a href="{% url 'list_countries' %}" class="nav-link">
                  <i class="fa fa-list-alt" aria-hidden="true"></i>&nbsp;
                  <p>Countries</p>
                </a>
              </li>
              {% endif %}
            </ul>
          </li>
          <!-- /Country Security Levels -->
          {% endif %}
          {% if perms.travelers.add_approver or perms.travelers.view_approver or perms.traveler.add_approvaldelegation %}
          <!-- Approvers -->
          <li class="nav-item">
            <a href="#" class="nav-link">
              <i class="fas fa-user-secret" aria-hidden="true"></i>
              <p>Approvers</p>
              <i class="right fas fa-angle-left"></i>
            </a>
            <ul class="nav nav-treeview">
              {% if perms.traveler.add_approver %}
              <li class="nav-item">
                <a href="{% url 'create_approver' %}" class="nav-link">
                  <i class="fa fa-plus" aria-hidden="true"></i>&nbsp;
                  <p>Add Approver</p>
                </a>
              </li>
              {% endif %}
              {% if perms.traveler.view_approver %}
              <li class="nav-item">
                <a href="{% url 'list_approvers' %}" class="nav-link">
                  <i class="fa fa-list-alt" aria-hidden="true"></i>&nbsp;
                  <p>Approvers</p>
                </a>
              </li>
              {% endif %}
              {% if perms.traveler.add_approvaldelegation %}
              <li class="nav-item">
                <a href="{% url 'delegate_approval' %}" class="nav-link">
                  <i class="fa fa-list-alt" aria-hidden="true"></i>&nbsp;
                  <p>Approval Delegation</p>
                </a>
              </li>
              {% endif %}
            </ul>
          </li>
            {% endif %}
        </ul>
      </nav>
      <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
  </aside>

  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1 class="m-0 text-dark">{{page_title}}</h1>
          </div><!-- /.col -->
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item">Home</li>
              <li class="breadcrumb-item active">{{page_title}}</li>
            </ol>
          </div><!-- /.col -->
        </div><!-- /.row -->
      </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->

    <!-- Main content -->
    <div class="content">
      <div class="container-fluid">
        <div class="row  justify-content-center">
          {% if messages %}
          <div class="col-12">
            {% for message in messages %}
            <div class="alert text-center {% if message.tags == 'error' %}alert-danger{%else%}alert-{{message.tags}}{%endif%} alert-dismissible fade show">
              <h6>
                {{message}}
              </h6>
              <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            {% endfor %}
          </div>
          {%endif %}
          {% block content %}
          {% endblock content %}
        </div>
        <!-- /.row -->
      </div><!-- /.container-fluid -->
    </div>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->

  <!-- Main Footer -->
  <footer class="main-footer">

  </footer>
</div>
<!-- ./wrapper -->

{% endblock body %}

backend/earo_travel_tracker/templates/foundation.html
{% load static %}
{% load widget_tweaks %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Kenya-Somalia Travel Tracker</title>

    <!-- Google Font: Source Sans Pro -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
    <!-- Font Awesome Icons -->
    <link rel="stylesheet" href="{% static 'plugins/fontawesome-free/css/all.min.css' %}">
    <!-- Bootstrap 4 style -->
    <link rel="stylesheet" href="{% static 'plugins/bootstrap/css/adminlte.min.css' %}">
    <!-- App universal -->
    <link rel="stylesheet" href="{% static 'dist/main.css' %}">
    <!-- select2 styles to add features to select fields -->
    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />

    <!-- Custom Styles -->
    {% block custom_styles %}

    {% endblock custom_styles %}

  </head>
    {% comment %}
    Always make sure to include an opening body tag when you extend this template.
    {%endcomment %}
    {% block body %}
    {% endblock body %}
    <!-- REQUIRED SCRIPTS -->

    <!-- jQuery -->
    <script src="{% static 'plugins/jquery/jquery.min.js' %}"></script>
    <!-- Bootstrap 4 -->
    <script src="{% static 'plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

    <script src="{% static 'plugins/bootstrap/js/adminlte.min.js' %}"></script>

    <!-- Select2 JS to add dynamic features to select fields -->
    <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
    {% block custom_scripts %}

    {% endblock custom_scripts %}
  </body>
</html>

backend/earo_travel_tracker/templates/render_form.html
{% load widget_tweaks %}
{% csrf_token %}
{% for hidden in form.hidden_fields %}
{{ hidden }}
{% endfor %}
{% for field in form.visible_fields %}
{% if field.errors %}
    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-6">
        <div class="form-group">
            <label for="{{ field.id_for_label }}">{{ field.label }}</label>
            {{ field | add_class:"form-control is-invalid" }}
            {% for error in field.errors %}
            <div class="invalid-feedback" style="display: block;">{{ error }}</div>
            {% endfor %}
        </div>
        
    </div>
 {% else %}
    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-6">
        <div class="form-group">
            <label for="{{ field.id_for_label }}">{{ field.label }}</label>
            {{ field | add_class:"form-control" }}
        </div>
    </div>
{% endif %}
{% endfor %}

backend/earo_travel_tracker/templates/render_form_full_width.html
{% load widget_tweaks%}
{% csrf_token %}
{% for hidden in form.hidden_fields %}
{{ hidden }}
{% endfor %}
{% for field in form.visible_fields %}
{% if field.errors %}
    <div class="col-12">
        <div class="form-group">
            <label for="{{ field.id_for_label }}">{{ field.label }}</label>
            {{ field | add_class:"form-control is-invalid" }}
            {% for error in field.errors %}
            <div class="invalid-feedback" style="display: block;">{{ error }}</div>
            {% endfor %}
        </div>
        
    </div>
 {% else %}
    <div class="col-12">
        <div class="form-group">
            <label for="{{ field.id_for_label }}">{{ field.label }}</label>
            {{ field | add_class:"form-control" }}
        </div>
    </div>
{% endif %}
{% endfor %}